image: node:6.9.4

options:
  size: 1x

definitions:
  caches:
    node-npm: ./node_modules

pipelines:
  default:
    - step:
        name: 'Default: @npm testing'
        caches:
          - node-npm
        script:
          - npm install
          - npm test


  branches:
    release/*:
      - step:
          name: 'Release: @npm testing'
          caches:
            - node-npm
          script:
            - npm install
            - npm test

    master:
      - step:
          name: 'Master: @npm testing'
          caches:
            - node-npm
          script:
            - npm install
            - npm test
      # - step:
      #     name: 'Master: npm publish'
      #     caches:
      #       - node-npm
      #     script:
      #       - npm install
      #       - git config --global user.email "phisit@readyplanet.com"
      #       - git config --global user.name "Phisit Kannasut@AUTO"
      #       - npm version patch
      #       - git push
      #       - npm publish
            